# Generated by Django 5.1.3 on 2024-12-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twigaapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerNotes',
        ),
    ]
