# Generated by Django 5.1.3 on 2024-12-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twigaapp', '0006_rename_bookingtype_bookings_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='manager_name',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
