# Generated by Django 5.1.3 on 2024-12-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twigaapp', '0007_alter_managers_manager_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='managers',
            name='manager_name',
            field=models.CharField(max_length=70),
        ),
    ]
